### ISSUE TITLE
Deluge 2 Support

### ISSUE THREAD

**Issue by tkdrob** [omaralvarez/deluge-autoremoveplus#50]
With Deluge 2 out, can we get this plugin updated to python 3 so we can use it?

**Comment by 1n5aN1aC** [comment]
Looks like there is an updated version here: https://github.com/kslr/deluge-autoremoveplus/

Unfortunately, it does not appear to compile without errors on python 3.7

It looks like kslr started working on updating it and gave up shortly after.....
I have found a guide here:  https://deluge.readthedocs.io/en/latest/devguide/how-to/update-1.3-plugin.html
I might possibly work on updating this, but I know nothing about GTK, and I'm only so-so on python 3, so I'm not confident I'll make any progress.

**Comment by maximberezin97** [comment]
I just submitted a pull request. Here is the egg: https://github.com/omaralvarez/deluge-autoremoveplus/files/3312651/AutoRemovePlus-0.6.2-py3.7.zip

**Comment by 1n5aN1aC** [comment]
Appears to be working.

I do have many torrents to do a full test on it right now, but it appears to be good to go!

Will update this or the pull request if I encounter any issues.

**Comment by alculete** [comment]
> I just submitted a pull request. Here is the egg: https://github.com/omaralvarez/deluge-autoremoveplus/files/3312651/AutoRemovePlus-0.6.2-py3.7.zip

It didn't work for me :-(

**Comment by deakster** [comment]
> > I just submitted a pull request. Here is the egg: https://github.com/omaralvarez/deluge-autoremoveplus/files/3312651/AutoRemovePlus-0.6.2-py3.7.zip
> 
> It didn't work for me :-(

Me neither, although it seems like the webui plugin upload thing isn't quite working properly in deluge for me...

**Comment by 1n5aN1aC** [comment]
I can confirm it is still working for me, including exemptions.

I manually put the plugin .egg into the plugins directory and restarted deluge.  I did not use the WebUI plugin upload functionality.

EDIT:  I did download the link from [here](https://github.com/omaralvarez/deluge-autoremoveplus/pull/51) I believe the link above in this thread used to be a broken version, but he edited it for the fixed version.

**Comment by demigh0d** [comment]
Tried installing manually and deluge throws the following error as soon as I click to enable it.

`13:12:04 [ERROR   ][deluge.pluginmanagerbase      :154 ] Unable to instantiate plugin 'AutoRemovePlus' from '/home/deluge/.config/deluge/plugins/AutoRemovePlus-0.6.2-py3.7.egg'!
13:12:04 [ERROR   ][deluge.pluginmanagerbase      :1418] No module named 'core'
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/deluge/pluginmanagerbase.py", line 148, in enable_plugin
    instance = cls(plugin_name.replace('-', '_'))
  File "/home/deluge/.config/deluge/plugins/AutoRemovePlus-0.6.2-py3.7.egg/autoremoveplus/__init__.py", line 46, in __init__
    from core import Core as _plugin_cls
ModuleNotFoundError: No module named 'core'`

**Comment by maximberezin97** [comment]
> Tried installing manually and deluge throws the following error as soon as I click to enable it.
> 
> `13:12:04 [ERROR ][deluge.pluginmanagerbase :154 ] Unable to instantiate plugin 'AutoRemovePlus' from '/home/deluge/.config/deluge/plugins/AutoRemovePlus-0.6.2-py3.7.egg'! 13:12:04 [ERROR ][deluge.pluginmanagerbase :1418] No module named 'core' Traceback (most recent call last): File "/usr/lib/python3/dist-packages/deluge/pluginmanagerbase.py", line 148, in enable_plugin instance = cls(plugin_name.replace('-', '_')) File "/home/deluge/.config/deluge/plugins/AutoRemovePlus-0.6.2-py3.7.egg/autoremoveplus/__init__.py", line 46, in __init__ from core import Core as _plugin_cls ModuleNotFoundError: No module named 'core'`

The error appears to come from an issue outside the scope of this plugin. If the plugin is unable to find the core module, then there are bigger issues at play. Please try a clean install/config/image depending on your setup, and make sure that you're using the most recent egg -- my edit in my previous comment changed the link to a build of an updated commit. Here is the most up-to-date egg: https://github.com/omaralvarez/deluge-autoremoveplus/files/3312651/AutoRemovePlus-0.6.2-py3.7.zip

**Comment by deakster** [comment]
I am using the linuxserver/deluge docker image, which is a very popular distribution of deluge (has over 10 million pulls), and it's on docker so it's pretty much consistent across all it's users, and therefore easy to recreate.

Dropping the egg into the plugins folder doesn't work, although I have no errors in the logs either.

**Comment by maximberezin97** [comment]
> I am using the linuxserver/deluge docker image, which is a very popular distribution of deluge (has over 10 million pulls), and it's on docker so it's pretty much consistent across all it's users, and therefore easy to recreate.
> 
> Dropping the egg into the plugins folder doesn't work, although I have no errors in the logs either.

I am familiar with both the linuxserver/deluge and binhex/arch-delugevpn images as well as the checksum-verified consistency of Docker images. Nevertheless, everyone has different configs that may have all sorts of effects.
Please try manually editing your core.conf and core.conf~ configs and adding a line for AutoRemovePlus to the enabled_plugins setting. I have experienced many times that Deluge may add the plugin to the plugins/ directory and fail to enable it in the config. I have also seen that the enabled_plugins key-value pair is not persistent between restarts.
For reference, my enabled_plugins key-value in both core.conf and core.conf~ looks like this:
`"enabled_plugins": [
        "Execute",
        "AutoRemovePlus",
        "Label",
        "Extractor"
    ],`

**Comment by deakster** [comment]
I had "enabled_plugins": ["Label", "AutoRemovePlus"], but no sign of the plugin working or appearing in the preferences page.

**Comment by maximberezin97** [comment]
> I had "enabled_plugins": ["Label", "AutoRemovePlus"], but no sign of the plugin working or appearing in the preferences page.

Is there a difference between the enabled_plugins values in core.conf~ and core.conf? Or did they both contain Label and AutoRemovePlus without needing to make any changes?
Nothing coming up in the logs?

**Comment by deakster** [comment]
Nothing in the logs. I added it to the core.conf~ file manually it wasn't there. Although my understanding was that file was just a backup anyway? The core.conf~ file's last modified date was a long time ago for me.

**Comment by demigh0d** [comment]
> > Tried installing manually and deluge throws the following error as soon as I click to enable it.
> > `13:12:04 [ERROR ][deluge.pluginmanagerbase :154 ] Unable to instantiate plugin 'AutoRemovePlus' from '/home/deluge/.config/deluge/plugins/AutoRemovePlus-0.6.2-py3.7.egg'! 13:12:04 [ERROR ][deluge.pluginmanagerbase :1418] No module named 'core' Traceback (most recent call last): File "/usr/lib/python3/dist-packages/deluge/pluginmanagerbase.py", line 148, in enable_plugin instance = cls(plugin_name.replace('-', '_')) File "/home/deluge/.config/deluge/plugins/AutoRemovePlus-0.6.2-py3.7.egg/autoremoveplus/__init__.py", line 46, in __init__ from core import Core as _plugin_cls ModuleNotFoundError: No module named 'core'`
> 
> The error appears to come from an issue outside the scope of this plugin. If the plugin is unable to find the core module, then there are bigger issues at play. Please try a clean install/config/image depending on your setup, and make sure that you're using the most recent egg -- my edit in my previous comment changed the link to a build of an updated commit. Here is the most up-to-date egg: https://github.com/omaralvarez/deluge-autoremoveplus/files/3312651/AutoRemovePlus-0.6.2-py3.7.zip

I'm rebuilding my media server so this is a new computer, fresh OS/Deluge install, First 3rd-party plugin to be installed. 

DISTRIB_DESCRIPTION="Ubuntu 19.04"

deluge-common/disco,now 2.0.3-2~201906121747~ubuntu19.04.1 all [installed,automatic]
deluge-console/disco,now 2.0.3-2~201906121747~ubuntu19.04.1 all [installed]
deluge-gtk/disco,now 2.0.3-2~201906121747~ubuntu19.04.1 all [installed,automatic]
deluge-torrent/disco,now 1.3.15-2 all [installed]
deluge-web/disco,now 2.0.3-2~201906121747~ubuntu19.04.1 all [installed,automatic]
deluge-webui/disco,now 1.3.15-2 all [installed]
deluge/disco,now 2.0.3-2~201906121747~ubuntu19.04.1 all [installed]
deluged/disco,now 2.0.3-2~201906121747~ubuntu19.04.1 all [installed]

I'll give the latest egg a try...

**Comment by maximberezin97** [comment]
> Nothing in the logs. I added it to the core.conf~ file manually it wasn't there. Although my understanding was that file was just a backup anyway? The core.conf~ file's last modified date was a long time ago for me.

Yes, core.conf~ is a backup. In my experience, sometimes there's an inexplicable difference between what Deluge loads and what core.conf says it should load. My guess was that it failed to use core.conf and fell back to using core.conf~, but this is most likely not the case. It is my own habit to add the plugins to both files.


> > > Tried installing manually and deluge throws the following error as soon as I click to enable it.
> > > `13:12:04 [ERROR ][deluge.pluginmanagerbase :154 ] Unable to instantiate plugin 'AutoRemovePlus' from '/home/deluge/.config/deluge/plugins/AutoRemovePlus-0.6.2-py3.7.egg'! 13:12:04 [ERROR ][deluge.pluginmanagerbase :1418] No module named 'core' Traceback (most recent call last): File "/usr/lib/python3/dist-packages/deluge/pluginmanagerbase.py", line 148, in enable_plugin instance = cls(plugin_name.replace('-', '_')) File "/home/deluge/.config/deluge/plugins/AutoRemovePlus-0.6.2-py3.7.egg/autoremoveplus/__init__.py", line 46, in __init__ from core import Core as _plugin_cls ModuleNotFoundError: No module named 'core'`
> > 
> > 
> > The error appears to come from an issue outside the scope of this plugin. If the plugin is unable to find the core module, then there are bigger issues at play. Please try a clean install/config/image depending on your setup, and make sure that you're using the most recent egg -- my edit in my previous comment changed the link to a build of an updated commit. Here is the most up-to-date egg: https://github.com/omaralvarez/deluge-autoremoveplus/files/3312651/AutoRemovePlus-0.6.2-py3.7.zip
> 
> I'm rebuilding my media server so this is a new computer, fresh OS/Deluge install, First 3rd-party plugin to be installed.
> 
> DISTRIB_DESCRIPTION="Ubuntu 19.04"
> 
> deluge-common/disco,now 2.0.3-2~201906121747~ubuntu19.04.1 all [installed,automatic]
> deluge-console/disco,now 2.0.3-2~201906121747~ubuntu19.04.1 all [installed]
> deluge-gtk/disco,now 2.0.3-2~201906121747~ubuntu19.04.1 all [installed,automatic]
> deluge-torrent/disco,now 1.3.15-2 all [installed]
> deluge-web/disco,now 2.0.3-2~201906121747~ubuntu19.04.1 all [installed,automatic]
> deluge-webui/disco,now 1.3.15-2 all [installed]
> deluge/disco,now 2.0.3-2~201906121747~ubuntu19.04.1 all [installed]
> deluged/disco,now 2.0.3-2~201906121747~ubuntu19.04.1 all [installed]
> 
> I'll give the latest egg a try...

~~What version of Deluge are you using? Did you install it from `apt-get install` or the deluge-torrent.org website? If you did install via `apt-get install`, did you get it from the default Ubuntu repositories or did you add the [Deluge Ubuntu PPA?](https://dev.deluge-torrent.org/wiki/Installing/Linux/Ubuntu#AddDelugePPARepository) It;s possible that the official Ubuntu repositories haven't updated Deluge to 2.0 yet, and it sounds to me like you may be using Deluge 1, because GTK and Python 3 changed the way the core module is used.~~

Nevermind, those versions listed are 2.0.3, up to date. Not sure what else could be causing this. Although it still may be worth checking if you're installing from the official Ubuntu repository or the Deluge PPA.

**Comment by wogam** [comment]
> > > Tried installing manually and deluge throws the following error as soon as I click to enable it.
> > > `13:12:04 [ERROR ][deluge.pluginmanagerbase :154 ] Unable to instantiate plugin 'AutoRemovePlus' from '/home/deluge/.config/deluge/plugins/AutoRemovePlus-0.6.2-py3.7.egg'! 13:12:04 [ERROR ][deluge.pluginmanagerbase :1418] No module named 'core' Traceback (most recent call last): File "/usr/lib/python3/dist-packages/deluge/pluginmanagerbase.py", line 148, in enable_plugin instance = cls(plugin_name.replace('-', '_')) File "/home/deluge/.config/deluge/plugins/AutoRemovePlus-0.6.2-py3.7.egg/autoremoveplus/__init__.py", line 46, in __init__ from core import Core as _plugin_cls ModuleNotFoundError: No module named 'core'`
> > 
> > 
> > The error appears to come from an issue outside the scope of this plugin. If the plugin is unable to find the core module, then there are bigger issues at play. Please try a clean install/config/image depending on your setup, and make sure that you're using the most recent egg -- my edit in my previous comment changed the link to a build of an updated commit. Here is the most up-to-date egg: https://github.com/omaralvarez/deluge-autoremoveplus/files/3312651/AutoRemovePlus-0.6.2-py3.7.zip
> 
> I'm rebuilding my media server so this is a new computer, fresh OS/Deluge install, First 3rd-party plugin to be installed.
> 
> DISTRIB_DESCRIPTION="Ubuntu 19.04"
> 
> deluge-common/disco,now 2.0.3-2~201906121747~ubuntu19.04.1 all [installed,automatic]
> deluge-console/disco,now 2.0.3-2~201906121747~ubuntu19.04.1 all [installed]
> deluge-gtk/disco,now 2.0.3-2~201906121747~ubuntu19.04.1 all [installed,automatic]
> deluge-torrent/disco,now 1.3.15-2 all [installed]
> deluge-web/disco,now 2.0.3-2~201906121747~ubuntu19.04.1 all [installed,automatic]
> deluge-webui/disco,now 1.3.15-2 all [installed]
> deluge/disco,now 2.0.3-2~201906121747~ubuntu19.04.1 all [installed]
> deluged/disco,now 2.0.3-2~201906121747~ubuntu19.04.1 all [installed]
> 
> I'll give the latest egg a try...

Try

`Python3 -V`

If it's 3.6.8, rename the file to 

> AutoRemovePlus-0.6.2-py3.6.egg

**Comment by tonytwostep** [comment]
Hey everyone, reporting in using Deluge 2.0.3 in a docker container based off of the archlinux/delugevpn image. Just used the latest AutoRemovePlus-0.6.2-py3.7 manually placed it in my plugins directory and rebooted deluge. 

The plugin showed up in the list and is working as expected. Great work.

**Comment by ardevd** [comment]
If you're using the `linuxserver/deluge` docker image you will need to rename `AutoRemovePlus-0.6.2-py3.7.egg` to `AutoRemovePlus-0.6.2-py3.6.egg` when placing it in the plugins directory. After doing this and restarting the docker container the plugin showed up.

**Comment by WrayOfSunshine** [comment]
> I just submitted a pull request. Here is the egg: https://github.com/omaralvarez/deluge-autoremoveplus/files/3312651/AutoRemovePlus-0.6.2-py3.7.zip

I pulled your egg and have it installed on the GTK version of Deluge, however I'm not sure how to config. I don't get a config option in the menu and the .conf is unfortunately not very clear. I don't mind just using the .conf directly if you can clarify the options.

**Comment by simpat1zq** [comment]
I can't get this egg to install at all. I did it through the web interface first, and the plugin didn't show up. Then I did it through the gui and still doesn't show up in the plugin list. I copied the egg to the plugins folder and restarted deluge, and that didn't work either. 

I'm running it on Ubuntu 19. Any ideas as to what I'm doing wrong?

**Comment by ardevd** [comment]
Check your python version. If you're on 3.6 you'll have to rename the egg.

**Comment by simpat1zq** [comment]
I had just fixed it and was typing it up when you posted that. The Python version fixed it. That said, are the settings supposed to show up in the GUI or is it supposed to be all manually editing the config files?

**Comment by ardevd** [comment]
Should show up in the web UI, yeah. You might have to enable it first under the plug-in menu.

**Comment by simpat1zq** [comment]
> Should show up in the web UI, yeah. You might have to enable it first under the plug-in menu.

I did that. And the plugin is definitely working(I used the old 1.x config file for it). But it just doesn’t show up in options.

**Comment by WrayOfSunshine** [comment]
I have the plugin at least theoretically working, but in the standalone GTK client the options menu doesn't appear (the "built-in" plugins do appear when selected). Is there any info on how to just hand craft the .conf, or a solution to make the menu appear?

Image: https://i.imgur.com/d64cAzi.png

**Comment by simpat1zq** [comment]
Does anyone else have a problem where the items don't actually get removed until you log into Deluge? For example, when I try to delete a downloaded file from the file system, I can't delete it because it's in use. So I log into Deluge, and I see it for a few seconds and then it disappears, and then I can delete it from the system.

**Comment by bobbyromeo** [comment]
Having a problem where this plugin doesn't remove anything. Same settings as with deluge 1.3.16. I see :39:29 [WARNING ][deluge.plugin.autoremoveplus.core:133 ] check interval loop starting in the log once I restart the docker, and never again.

**Comment by trevor-s8** [comment]
> 
> 
> I have the plugin at least theoretically working, but in the standalone GTK client the options menu doesn't appear (the "built-in" plugins do appear when selected). Is there any info on how to just hand craft the .conf, or a solution to make the menu appear?
> 
> Image: https://i.imgur.com/d64cAzi.png

Same here. The .conf from the previous version seems to work fine for me though. I'd suggest installing deluge 1.0, grabbing the old version of the .egg, creating the config you want, then converting to deluge 2.0 until the settings page is updated. Incredibly poor work around, but it's better than trying to figure out the .conf syntax.

**Comment by kevindd992002** [comment]
> 
> 
> Having a problem where this plugin doesn't remove anything. Same settings as with deluge 1.3.16. I see :39:29 [WARNING ][deluge.plugin.autoremoveplus.core:133 ] check interval loop starting in the log once I restart the docker, and never again.

I have the exact same problem! It works once and then when the docker container restarts it never does what it's supposed to until you manually change the settings and apply again. Can the devs comment here please?

**Comment by springjools** [comment]
I could update the plugin for python 3.7 and deluge 2, but there are just two problems:
1) can't yet install deluge 2 for arm debian (raspberry)
2) cannot create an account to write on the forum (the secret question doesn't accept the right answer).

**Comment by bendikro** [comment]
@springjools 
_The Deluge Team_ doesn't work?

**Comment by springjools** [comment]
No. The question is:

What answer to the above question is named after a person?:
This question is a means of preventing automated form submissions by spambots.

"Debian 8, the old old stable, was named Jessie after the cowgirl in Toy Story 2, Toy Story 3 and Toy Story 4."

**Comment by bendikro** [comment]
@springjools 
I see. Try Linux

**Comment by springjools** [comment]
Thanks. It worked. Overcomplicating things as usual.

**Comment by kevindd992002** [comment]
> 
> 
> > Having a problem where this plugin doesn't remove anything. Same settings as with deluge 1.3.16. I see :39:29 [WARNING ][deluge.plugin.autoremoveplus.core:133 ] check interval loop starting in the log once I restart the docker, and never again.
> 
> I have the exact same problem! It works once and then when the docker container restarts it never does what it's supposed to until you manually change the settings and apply again. Can the devs comment here please?

Can you guys please fix this?!

**Comment by springjools** [comment]
Hello,

Is the plugin author still active? Otherwise maybe it's best to make a
new plugin, specially since there are some mods of this plugin out there
(ABIROID MOD eg). The question is what this plugin should really do.

And should it support python 3?

/Jools

**Comment by kevindd992002** [comment]
Beats me. I'm new to Deluge and I know that I need this plugin, so.

**Comment by springjools** [comment]
I'm working on this plugin but I made some modifications, I'm not sure
everybody wants these things.

I implemented the abiroid mod
(https://www.invitehawk.com/topic/62648-deluge-using-autoremoveplus-to-auto-delete-old-torrents/?tab=comments#comment-216331),
which can also remove unfinished torrents. But then it disabled the
removal of seeding torrents, so I added that back as a separate option.

Then I also want to communicate bacl´k to sonarr/radarr that the
downlaod has failed, I don't know if many people use those, but I want
to be able to blacklist a release from deluge, so that it doesn't
downlaod the same version again.

But I'm working with deluge 1.3.15, not sure if i can upgrade to deliuge 2.0

/Jools

**Comment by ghost** [comment]
Any progress on this @springjools? I wouldn't worry about what people want at this stage. Any progress is better than this repo being stale for the last 3 years.

As for the sonnarr/radarr stuff, I would love that, and I feel a lot of people use those services so would love that addon too!

Hopefully, you will find a way to develop it for deluge 2.0 also. I'm happy to provide debug support!

**Comment by springjools** [comment]
I managed to make the sonarr/radarr/lidarr interaction work when the calling in python in a standalone shell, but when I make the call in the plugin I get a HTTP 500 error. I think something in the call is making deluged crash. But that was with deluge 1.3.15. Now I just managed to update to deluge 2.0.3 and I have to first make the plugin work with this deluge version before I can test further.

**Comment by springjools** [comment]
I got it working now on python 3. Just hold on for a while while I move out hardcoded stuff into options. I also haven't tested it yet for any bugs but it's running right now at least.

**Comment by ghost** [comment]
@springjools Fantastic! Thanks for your work!

**Comment by springjools** [comment]
There's an updated version here now: https://github.com/springjools/deluge-autoremoveplus

**Comment by isklikas** [comment]
> There's an updated version here now: https://github.com/springjools/deluge-autoremoveplus

Hi! Thank you for your good work! I just can't get it to work I'm afraid... I am using linuxserver/deluge docker container. I initially tried with the egg file in your releases tab and it did show on Web UI, under plugins, but I couldn't enable it, if I check it and press ok, when I look at plugins again, it's unchecked.

After that, I cloned your git repo and built the egg file myself. The same thing happened unfortunately, it shows up perfectly under Plugins, but enabling it does nothing. I have tried also adding it manually to core.conf (and core.conf.bak). My enabled_plugins line looks like:

` "enabled_plugins": [
        "AutoAdd",
        "AutoRemovePlus",
        "Label"
    ]`

and yet the plugin still doesn't show. The logs don't show anything, it's as if the entry isn't there. Any ideas? There is no AutoRemovePlus.conf file as the README suggests, so I really don't understand why this is happening. Thank you for your help.

**Comment by springjools** [comment]
Hello, probably some bug then, as i worked in an environment that had always had that plugin and never tried it on a clean environment. Which logs did you check? I have found that deluge puts a lot of things also in /var/log/daemon.log and also maybe in /var/log/syslog. Check those as well.

Also look in the web browser’s console. Firefox has it in tools->development->console or something similar.

**Comment by spacezorro** [comment]
@springjools 

I am failing at "from .mediaserver import Mediaserver"

: [ERROR   ][deluge.pluginmanagerbase      :1343] No module named 'autoremoveplus.mediaserver'
: Traceback (most recent call last):
:   File "/usr/lib/python3/dist-packages/deluge/pluginmanagerbase.py", line 148, in enable_plugin
:     instance = cls(plugin_name.replace('-', '_'))
:   File "/home/net/.config/deluge/plugins/AutoRemovePlus-0.6.6-py3.6.egg/autoremoveplus/__init__.py", line 48, in __init__
:     from autoremoveplus.core import Core as _plugin_cls
:   File "/home/usenet/.config/deluge/plugins/AutoRemovePlus-0.6.6-py3.6.egg/autoremoveplus/core.py", line 51, in <module>
:     from .mediaserver import Mediaserver
: ModuleNotFoundError: No module named 'autoremoveplus.mediaserver'

Where do I get mediaserver.py?

**Comment by ghost** [comment]
@springjools I have a slightly different error. Same sysmptoms as @isklikas, but I have an error log:

```
08:27:34.178 [ERROR   ][deluge.pluginmanagerbase      :79  ] Unable to instantiate plugin 'AutoRemovePlus' from '/config/plugins/AutoRemovePlus-0.6.6.egg'!
08:27:34.179 [ERROR   ][deluge.pluginmanagerbase      :79  ] No module named 'past'
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/deluge/pluginmanagerbase.py", line 148, in enable_plugin
    instance = cls(plugin_name.replace('-', '_'))
  File "/config/plugins/AutoRemovePlus-0.6.6.egg/autoremoveplus/__init__.py", line 48, in __init__
    from autoremoveplus.core import Core as _plugin_cls
  File "<frozen zipimport>", line 259, in load_module
  File "/config/plugins/AutoRemovePlus-0.6.6.egg/autoremoveplus/core.py", line 45, in <module>
    from past.utils import old_div
ModuleNotFoundError: No module named 'past'
```

**Comment by spacezorro** [comment]
@cheesemarathon install python3-future

**Comment by springjools** [comment]
Oh fuck, I forgot to add a bunch of stuff to the release, no wonder it's not working. I just copied the folder to the cloned repo and pushed the diff, but github didn't automatically add new files. Here they are now.

But the .egg should still contain everything? Anyway, try now with these files. 

And yes, some modules were added to maintain compatibility with both python 3 and 2, I think the past module is only needed for that old python 2 style division, which is probably not wanted anyway. In the ideal world, one should rewrite this whole plugin from scratch.

But  it works now at least. I think the errors that happen when removing torrents are due to something trying to remove them twice. They do actually get removed still, but there is some error.

**Comment by simpat1zq** [comment]
@springjools Thanks for this, but I've been trying the egg file for a couple days, but the plugin never enables. I check the box, click Apply, but when I come back to the preferences, it's unchecked again. 

EDIT: I forgot to mention that I'm using the webui.

**Comment by springjools** [comment]
But there has to be a mention of that in some log. I had this several times when testing and it's something that crashes...

**Comment by springjools** [comment]
I mean it could be a new config value that isn't populated or so, I should test this with a clean environment. I'm also using web-ui and linux (raspbian)

**Comment by simpat1zq** [comment]
@springjools And now, for some reason, it won't even let me check the box to enable the plugin. Less than a second after I check it, the check box disappears.

**Comment by springjools** [comment]
Try this one: now I tested it on my deluge 1.3.15 as well.
https://github.com/springjools/deluge-autoremoveplus/releases/tag/0.6.7

The:
ModuleNotFoundError: No module named 'past'
Error is fixed by running the command 'pip install future', but I had to do this with the same user as is running the deluge daemon/client, in my case it's run under the deluge user in linux, so I had to run that command under that user.

**Comment by simpat1zq** [comment]
Awesome. Now it stays enabled. I restarted Deluge, and it's still enabled, but it still doesn't show the addon settings in preferences. Do we need to manually edit the config files?

**Comment by springjools** [comment]
No, but I think you may need to reload the web-ui and maybe restart deluge daemon/client after enabling the new version of the plugin. Try shift-F5 to reload the web page as well. I also had to remove the old .egg from /var/lib/deluge/.config/deluge/plugins/ folder, or wherever you have that folder.

**Comment by simpat1zq** [comment]
Awesome. Restarting the Web-ui was the fix. I had tried the other stuff and that didn't do it. But it's all there now. I'll try out the actual auto-removing later today.

**Comment by springjools** [comment]
Btw, that test button on the last tab doesn't do anything. I'm not very good at javascript so I can't really write a post-method in it. Ideally it would send a get request to the servers and return the response, but for now you will have to check the logs instead.

**Comment by simpat1zq** [comment]
@springjools So it looks like this plugin works when I have the webUI open in a web browser. However, if it's not, then the torrents stay there until I manually connect through the webUI. Any idea why that's happening?

**Comment by springjools** [comment]
Have you chosen to remove them? Delete them or pause them? Anything in the logs?

**Comment by HashSquatch** [comment]
@springjools 2 things need to be addressed with your version of the egg. python-future dependency and new corrupt config generation where the config has missing key pair values for sonnar, radarr and lidarr.

**Comment by springjools** [comment]
Are you commenting on the latest version of the plugin, ie 0.6.7?

Because i added a check like that on the second point you write about.

**Comment by TheMrRandomDude** [comment]
@springjools Hello. I also tried out that plugin in my Deluge. Same issue, I enable it and it disables itself. (Version 0.6.7).

**Comment by springjools** [comment]
> 
> 
> @springjools So it looks like this plugin works when I have the webUI open in a web browser. However, if it's not, then the torrents stay there until I manually connect through the webUI. Any idea why that's happening?

Are you aware of this: https://dev.deluge-torrent.org/ticket/3335

**Comment by maxwell-01** [comment]
@springjools hello - firstly thank you for picking up this work. It's been a real headache since deluge stopped removing torrents.

I am using binhex/arch-delugevpn and I cannot seem to get this to work. Cloned your repo and compiled the egg file as in the instructions then tried uploading through the UI and by manually placing the egg into the plugins folder. Additionally tried a completely fresh container and still couldn't get it to work.

Can you let me know if it works for you within the arch-delugevpn docker?

**Comment by shadycuz** [comment]
@simpat1zq @springjools 

I also have that issue. 

Torrents dont delete unless I connect to the gui, open the plugin settings and click apply. Then torrents delete.

Any idea for a fix? @springjools I think that link is for the "built-in" method for deleting torrents and not for this plugin.

**Comment by springjools** [comment]
@shadycuz : The plugin uses the built-in method to delete torrents. See: 

**https://github.com/springjools/deluge-autoremoveplus/blob/856ce13346c9249b89140a59a359dc952c59ad33/autoremoveplus/core.py#L248**

**Comment by shadycuz** [comment]
@springjools aha I see. So they are probably all being queued up to be deleted, but it's not working unless you have the web gui open. =/

**Comment by springjools** [comment]
Do you have anything in the logs? This plugins writes in the log when the removal happens.

**Comment by sirdangles** [comment]
I am having issues when trying to install autoremoveplus to a binhex-deluge 2.0.3 docker container.  Whenever I try and add the 0.6.8 (or 0.6.7 and 0.6.6) egg, it doesn't show up in the plugins.  Am I doing something incorrectly?

**Comment by springjools** [comment]
Check what the logs say.

**Comment by sirdangles** [comment]
> Check what the logs say.

There doesn't seem to be anything in the logs.  I have just setup the deluge container, so I am a bit new to this.  I am running it in unraid, and when I check the log icon next to the container, it never references the .egg file or plugins in general.

**Comment by badbonez** [comment]
> If you're using the `linuxserver/deluge` docker image you will need to rename `AutoRemovePlus-0.6.2-py3.7.egg` to `AutoRemovePlus-0.6.2-py3.6.egg` when placing it in the plugins directory. After doing this and restarting the docker container the plugin showed up.

Yes!  Thank you.

**Comment by teflocarbon** [comment]
For those having issues on linuxserver/deluge with enabling the plugin going in and out and its unticked.
Exec this into the container.
`apt-get update && apt-get install -y python3-requests python3-future`

**Comment by kevindd992002** [comment]
That's weird. I did not have to do that and it worked on my container.

**Comment by unixfox** [comment]
Not really a good idea @teflocarbon. Containers are temporary and once the image will be updated you will loose the packages that you installed manually.

**Comment by kevindd992002** [comment]
> 
> 
> Not really a good idea @teflocarbon. Containers are temporary and once the image will be updated you will loose the packages that you installed manually.

That's very easy to solve with LSIO containers:

https://blog.linuxserver.io/2019/09/14/customizing-our-containers/

**Comment by unixfox** [comment]
> > Not really a good idea @teflocarbon. Containers are temporary and once the image will be updated you will loose the packages that you installed manually.
> 
> That's very easy to solve with LSIO containers:
> 
> [blog.linuxserver.io/2019/09/14/customizing-our-containers](https://blog.linuxserver.io/2019/09/14/customizing-our-containers/)

I think it's better to upstream the command to the initial image than doing it the hacky way.

**Comment by kevindd992002** [comment]
> 
> 
> > > Not really a good idea @teflocarbon. Containers are temporary and once the image will be updated you will loose the packages that you installed manually.
> > 
> > 
> > That's very easy to solve with LSIO containers:
> > [blog.linuxserver.io/2019/09/14/customizing-our-containers](https://blog.linuxserver.io/2019/09/14/customizing-our-containers/)
> 
> I think it's better to upstream the command to the initial image than doing it the hacky way.

Well, yes, of course that's the best way but that's up to the LSIO team to do it. In my case, I did not need to install anything to make the plugin work so I'm not sure if installing it is even applicable for all. 

I'm just saying that if you have to do any customization to their containers, you can easily but a two-liner sh script in the `custom-cont-init.d` folder in the container's config folder. I wouldn't call it some sort of "hacking", not even close. LSIO is nice enough to give customization options for their users. But yeah, to each his own.

**Comment by JoeStratton** [comment]
its definitely a hacky way, I agree. The appropriate way would be to fork it and do it yourself to the base image or create a pull request with the change.

**Comment by kevindd992002** [comment]
@teflocarbon So based on this [post](https://forum.deluge-torrent.org/viewtopic.php?f=9&t=47243&p=231559#p231558) only the python3-requests module is needed. Are you saying that you need to update it? And is the python3-future module really needed?

**Comment by springjools** [comment]
That's right. Only requests is needed. There's a requirements.txt that you can use as well. It's recommended that you also use the latest version of twisted, which is 20.3.0, if you want to be compatible with python 3.8 (because there's some error spam from earlier versions of twisted related to the logger module).

**Comment by kevindd992002** [comment]
> 
> 
> That's right. Only requests is needed. There's a requirements.txt that you can use as well. It's recommended that you also use the latest version of twisted, which is 20.3.0, if you want to be compatible with python 3.8 (because there's some error spam from earlier versions of twisted related to the logger module).

Ok. How do you exactly use the requirements.txt that you have on your branch? Are you saying to just use it as a reference, manually? Or is there some automation that I can do? Sorry, I'm not a Linux expert.

Also, I just installed python3-requests on the LSIO docker container but this is the latest module I got:

python3-requests/bionic-updates,bionic-security,now 2.18.4-2ubuntu0.1 all [installed]

In your requirements.txt, you have these:

```
colorama>=0.4.3
requests>=2.22.0
twisted>=19.7.0
urllib3>=1.25.8
```

So obviously, I have a lower version of requests installed even though I just installed it. I made sure to update the apt repository of course.

**Comment by springjools** [comment]
"pip3 install -r requirements.txt"

**Comment by springjools** [comment]
I don't think the requests matter so much, but using an old twisted and python 3.8 causes log spams. You may need to forcefully install latest twisted using the command:
"pip3 install twisted==20.3.0"

**Comment by kevindd992002** [comment]
Well, the thing is that LSIO's docker container uses python 3.6.9. So I really don't need to update the old twisted, do I?

**Comment by springjools** [comment]
Nope, but eventually it will use python 3.8 right?

**Comment by kevindd992002** [comment]
Yeah, I suppose so. It also doesn't have pip3. Do I need to manually install that or something? I almost always use just apt to install/remove things.

**Comment by springjools** [comment]
pip comes with python. On linux the relevant commands seem to be python3 and pip3 instead of the plain versions. In case you cannot use pip directly because of rights/other issues you can launch pip with the command 'python -m pip' or 'python3 -m pip'. 

Actually, if you upgrade to python 3.8 you also need to upgrade to deluge 2.04.dev24, since the issue with the new syntax for the logger module is fixed there. My experience is that deluge is a bit slow to upgrade things.

**Comment by kevindd992002** [comment]
```
root@8868a5590b05:/# python3 -m pip
/usr/bin/python3: No module named pip
```

**Comment by springjools** [comment]
Hmmm, weird. Can you test any of the fixes on this page:
https://askubuntu.com/questions/1025189/pip-is-not-working-importerror-no-module-named-pip-internal
